export const navFooterItems = [
    {
        title: 'Women',
        subcategories: [
            { name: 'Shirts', img: '/shirts.jpg', alt: 'Shirts Image', url: '/women/shirts' },
            { name: 'T-Shirts', img: '/tshirts.jpg', alt: 'T-Shirts Image', url: '/women/t-shirts' },
            { name: 'Sweaters', img: '/sweaters.jpg', alt: 'Sweaters Image', url: '/women/sweaters' },
            { name: 'Coats', img: '/Coats.jpg', alt: 'coats Image', url: '/women/coats' },
            { name: 'Suits', img: '/Suits.jpg', alt: 'suits Image', url: '/women/suits' },
            { name: 'Underwear', img: '/Underwear.jpg', alt: 'underwear Image', url: '/women/underwear' },
            { name: 'Socks', img: '/Socks.jpg', alt: 'socks Image', url: '/women/socks' },
            { name: 'Skirts', img: '/Skirts.jpg', alt: 'skirts Image', url: '/women/skirts' },
            { name: 'Pants', img: '/pants.jpg', alt: 'pants Image', url: '/women/pants' },
            { name: 'Swimwear', img: '/Swimwear.jpg', alt: 'swimwear Image', url: '/women/swimwear' },
        ],
    },
    {
        title: 'Men',
        subcategories: [
            { name: 'Shirts', img: '/menshirts.jpg', alt: 'Shirts Image', url: '/men/shirts' },
            { name: 'T-Shirts', img: '/mentshirts.jpg', alt: 'T-Shirts Image', url: '/men/t-shirts' },
            { name: 'Sweaters', img: '/sweaters.jpg', alt: 'sweaters Image', url: '/men/sweaters' },
            { name: 'Coats', img: '/Coats.jpg', alt: 'coats Image', url: '/men/coats' },
            { name: 'Suits', img: '/Suits.jpg', alt: 'suits Image', url: '/men/suits' },
            { name: 'Underwear', img: '/Underwear.jpg', alt: 'underwear Image', url: '/men/underwear' },
            { name: 'Socks', img: '/Socks.jpg', alt: 'socks Image', url: '/men/socks' },
            { name: 'Pants', img: '/pants.jpg', alt: 'pants Image', url: '/men/pants' },
            { name: 'Swimwear', img: '/Swimwear.jpg', alt: 'swimwear Image', url: '/men/swimwear' },
        ],
    },
    {
        title: 'Boy',
        subcategories: [
            { name: 'Shirts', img: '/menshirts.jpg', alt: 'Shirts Image', url: '/boy/shirts' },
            { name: 'T-Shirts', img: '/mentshirts.jpg', alt: 'T-Shirts Image', url: '/boy/t-shirts' },
            { name: 'Sweaters', img: '/sweaters.jpg', alt: 'sweaters Image', url: '/boy/sweaters' },
            { name: 'Coats', img: '/Coats.jpg', alt: 'coats Image', url: '/boy/coats' },
            { name: 'Suits', img: '/Suits.jpg', alt: 'suits Image', url: '/boy/suits' },
            { name: 'Underwear', img: '/Underwear.jpg', alt: 'underwear Image', url: '/boy/underwear' },
            { name: 'Socks', img: '/Socks.jpg', alt: 'socks Image', url: '/boy/socks' },
            { name: 'Pants', img: '/pants.jpg', alt: 'pants Image', url: '/boy/pants' },
            { name: 'Swimwear', img: '/Swimwear.jpg', alt: 'swimwear Image', url: '/boy/swimwear' },
        ],
    },
    {
        title: 'Girl',
        subcategories: [
            { name: 'Shirts', img: '/shirts.jpg', alt: 'Shirts Image', url: '/girl/shirts' },
            { name: 'T-Shirts', img: '/tshirts.jpg', alt: 'T-Shirts Image', url: '/girl/t-shirts' },
            { name: 'Sweaters', img: '/sweaters.jpg', alt: 'Sweaters Image', url: '/girl/sweaters' },
            { name: 'Coats', img: '/Coats.jpg', alt: 'coats Image', url: '/girl/coats' },
            { name: 'Suits', img: '/Suits.jpg', alt: 'suits Image', url: '/girl/suits' },
            { name: 'Underwear', img: '/Underwear.jpg', alt: 'underwear Image', url: '/girl/underwear' },
            { name: 'Socks', img: '/Socks.jpg', alt: 'socks Image', url: '/girl/socks' },
            { name: 'Skirts', img: '/Skirts.jpg', alt: 'skirts Image', url: '/girl/skirts' },
            { name: 'Pants', img: '/pants.jpg', alt: 'pants Image', url: '/girl/pants' },
            { name: 'Swimwear', img: '/Swimwear.jpg', alt: 'swimwear Image', url: '/girl/swimwear' },
        ],
    },
    {
        title: 'Summer',
        url: '/summer',
    },
    {
        title: 'Sales',
        url: '/sales',
    },
];