export const navFooterItems = [
    {
        title: 'Women',
        subcategories: [
            { name: 'Shirts', img: '/shirts.png', alt: 'Shirts Image', url: '/women/shirts' },
            { name: 'Tshirts', img: '/t-shirts.png', alt: 'T- Shirts Image', url: '/women/t-shirts' },
            { name: 'Sweaters', img: '/swearters.png', alt: 'Sweaters Image', url: '/women/sweaters' },
            { name: 'Coats', img: '/coats.png', alt: 'coats Image', url: '/women/coats' },
            { name: 'Suits', img: '/suitsw.png', alt: 'suits Image', url: '/women/suits' },
            { name: 'Underwear', img: '/underwear.png', alt: 'underwear Image', url: '/women/underwear' },
            { name: 'Socks', img: '/bootees.png', alt: 'socks Image', url: '/women/socks' },
            { name: 'Skirts', img: '/skirts.png', alt: 'skirts Image', url: '/women/skirts' },
            { name: 'Pants', img: '/pants.png', alt: 'pants Image', url: '/women/pants' },
            { name: 'Swimwear', img: '/Swimwearw.png', alt: 'swimwear Image', url: '/women/swimwear' },
        ],
    },
    {
        title: 'Men',
        subcategories: [
            { name: 'Shirts', img: '/shirts.png', alt: 'Shirts Image', url: '/men/shirts' },
            { name: 'Tshirts', img: '/t-shirts.png', alt: 'T-Shirts Image', url: '/men/t-shirts' },
            { name: 'Sweaters', img: '/swearters.png', alt: 'sweaters Image', url: '/men/sweaters' },
            { name: 'Coats', img: '/coats.png', alt: 'coats Image', url: '/men/coats' },
            { name: 'Suits', img: '/suitsm.png', alt: 'suits Image', url: '/men/suits' },
            { name: 'Underwear', img: '/boxers.png', alt: 'underwear Image', url: '/men/underwear' },
            { name: 'Socks', img: '/bootees.png', alt: 'socks Image', url: '/men/socks' },
            { name: 'Pants', img: '/pants.png', alt: 'pants Image', url: '/men/pants' },
            { name: 'Swimwear', img: '/swimwear.png', alt: 'swimwear Image', url: '/men/swimwear' },
        ],
    },
    {
        title: 'Boy',
        subcategories: [
            { name: 'Shirts', img: '/shirts.png', alt: 'Shirts Image', url: '/boy/shirts' },
            { name: 'Tshirts', img: '/t-shirts.png', alt: 'T-Shirts Image', url: '/boy/t-shirts' },
            { name: 'Sweaters', img: '/swearters.png', alt: 'sweaters Image', url: '/boy/sweaters' },
            { name: 'Coats', img: '/coats.png', alt: 'coats Image', url: '/boy/coats' },
            { name: 'Suits', img: '/suitsm.png', alt: 'suits Image', url: '/boy/suits' },
            { name: 'Underwear', img: '/boxers.png', alt: 'underwear Image', url: '/boy/underwear' },
            { name: 'Socks', img: '/bootees.png', alt: 'socks Image', url: '/boy/socks' },
            { name: 'Pants', img: '/pants.png', alt: 'pants Image', url: '/boy/pants' },
            { name: 'Swimwear', img: '/swimwear.png', alt: 'swimwear Image', url: '/boy/swimwear' },
        ],
    },
    {
        title: 'Girl',
        subcategories: [
            { name: 'Tshirts', img: '/t-shirts.png', alt: 'T-Shirts Image', url: '/girl/t-shirts' },
            { name: 'Sweaters', img: '/swearters.png', alt: 'Sweaters Image', url: '/girl/sweaters' },
            { name: 'Coats', img: '/coats.png', alt: 'coats Image', url: '/girl/coats' },
            { name: 'Suits', img: '/dress.png', alt: 'suits Image', url: '/girl/suits' },
            { name: 'Underwear', img: '/panties.png', alt: 'underwear Image', url: '/girl/underwear' },
            { name: 'Socks', img: '/bootees.png', alt: 'socks Image', url: '/girl/socks' },
            { name: 'Skirts', img: '/skirt.png', alt: 'skirts Image', url: '/girl/skirts' },
            { name: 'Pants', img: '/pants.png', alt: 'pants Image', url: '/girl/pants' },
            { name: 'Swimwear', img: '/swimsuit.png', alt: 'swimwear Image', url: '/girl/swimwear' },
        ],
    },
    {
        title: 'Summer',
        url: '/summer',
    },
    {
        title: 'Sales',
        url: '/sales',
    },
];