export const navFooterItems = [
    {
        id: 1,
        title: 'Women',
        link: "/pages/products/women",
        subcategories: [
            { id: 11, name: 'Shirts', img: '/shirts.png', alt: 'Shirts Image', url: '/women/shirts' },
            { id: 12, name: 'Tshirts', img: '/t-shirts.png', alt: 'T- Shirts Image', url: '/women/t-shirts' },
            { id: 13, name: 'Sweaters', img: '/swearters.png', alt: 'Sweaters Image', url: '/women/sweaters' },
            { id: 14, name: 'Coats', img: '/coats.png', alt: 'coats Image', url: '/women/coats' },
            { id: 15, name: 'Suits', img: '/suitsw.png', alt: 'suits Image', url: '/women/suits' },
            { id: 16, name: 'Underwear', img: '/underwear.png', alt: 'underwear Image', url: '/women/underwear' },
            { id: 17, name: 'Socks', img: '/bootees.png', alt: 'socks Image', url: '/women/socks' },
            { id: 18, name: 'Skirts', img: '/skirts.png', alt: 'skirts Image', url: '/women/skirts' },
            { id: 19, name: 'Pants', img: '/pants.png', alt: 'pants Image', url: '/women/pants' },
            { id: 111, name: 'Swimwear', img: '/Swimwearw.png', alt: 'swimwear Image', url: '/women/swimwear' },
        ],
    },
    {
        id: 2,
        title: 'Men',
        link: "/pages/products/men",
        subcategories: [
            { id: 21, name: 'Shirts', img: '/shirts.png', alt: 'Shirts Image', url: '/men/shirts' },
            { id: 22, name: 'Tshirts', img: '/t-shirts.png', alt: 'T-Shirts Image', url: '/men/t-shirts' },
            { id: 23, name: 'Sweaters', img: '/swearters.png', alt: 'sweaters Image', url: '/men/sweaters' },
            { id: 24, name: 'Coats', img: '/coats.png', alt: 'coats Image', url: '/men/coats' },
            { id: 25, name: 'Suits', img: '/suitsm.png', alt: 'suits Image', url: '/men/suits' },
            { id: 26, name: 'Underwear', img: '/boxers.png', alt: 'underwear Image', url: '/men/underwear' },
            { id: 27, name: 'Socks', img: '/bootees.png', alt: 'socks Image', url: '/men/socks' },
            { id: 28, name: 'Pants', img: '/pants.png', alt: 'pants Image', url: '/men/pants' },
            { id: 29, name: 'Swimwear', img: '/swimwear.png', alt: 'swimwear Image', url: '/men/swimwear' },
        ],
    },
    {
        id: 3,
        title: 'Boy',
        link: "/pages/products/boy",
        subcategories: [
            { id: 31, name: 'Shirts', img: '/shirts.png', alt: 'Shirts Image', url: '/boy/shirts' },
            { id: 32, name: 'Tshirts', img: '/t-shirts.png', alt: 'T-Shirts Image', url: '/boy/t-shirts' },
            { id: 33, name: 'Sweaters', img: '/swearters.png', alt: 'sweaters Image', url: '/boy/sweaters' },
            { id: 34, name: 'Coats', img: '/coats.png', alt: 'coats Image', url: '/boy/coats' },
            { id: 35, name: 'Suits', img: '/suitsm.png', alt: 'suits Image', url: '/boy/suits' },
            { id: 36, name: 'Underwear', img: '/boxers.png', alt: 'underwear Image', url: '/boy/underwear' },
            { id: 37, name: 'Socks', img: '/bootees.png', alt: 'socks Image', url: '/boy/socks' },
            { id: 38, name: 'Pants', img: '/pants.png', alt: 'pants Image', url: '/boy/pants' },
            { id: 39, name: 'Swimwear', img: '/swimwear.png', alt: 'swimwear Image', url: '/boy/swimwear' },
        ],
    },
    {
        id: 4,
        title: 'Girl',
        link: "/pages/products/girl",
        subcategories: [
            { id: 41, name: 'Tshirts', img: '/t-shirts.png', alt: 'T-Shirts Image', url: '/girl/t-shirts' },
            { id: 42, name: 'Sweaters', img: '/swearters.png', alt: 'Sweaters Image', url: '/girl/sweaters' },
            { id: 43, name: 'Coats', img: '/coats.png', alt: 'coats Image', url: '/girl/coats' },
            { id: 44, name: 'Suits', img: '/dress.png', alt: 'suits Image', url: '/girl/suits' },
            { id: 45, name: 'Underwear', img: '/panties.png', alt: 'underwear Image', url: '/girl/underwear' },
            { id: 46, name: 'Socks', img: '/bootees.png', alt: 'socks Image', url: '/girl/socks' },
            { id: 47, name: 'Skirts', img: '/skirt.png', alt: 'skirts Image', url: '/girl/skirts' },
            { id: 48, name: 'Pants', img: '/pants.png', alt: 'pants Image', url: '/girl/pants' },
            { id: 49, name: 'Swimwear', img: '/swimsuit.png', alt: 'swimwear Image', url: '/girl/swimwear' },
        ],
    },
    {
        id: 5,
        title: 'Summer',
        link: "/",
    },
    {
        id: 6,
        title: 'Winter',
        link: "/",
    },
];